# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/trashCan/Projects/Assign/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/trashCan/Projects/Assign/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  E:/trashCan/Projects/Assign/tuturu.v
  E:/trashCan/Projects/Assign/tb.v
  E:/trashCan/Projects/Assign/fp_add.v
  E:/trashCan/Projects/Assign/fp_add_tb.v
}
synth_design -top fp_add -part xc7z020clg400-1
write_checkpoint -noxdef fp_add.dcp
catch { report_utilization -file fp_add_utilization_synth.rpt -pb fp_add_utilization_synth.pb }
