# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/tuturu.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/tb.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/fp_add.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/fp_add_tb.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/project_1/project_1.sim/sim_1/behav/glbl.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/PE_FC_ANN.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/weights_Memory.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/FC_Layer_ANN.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/project_1/project_1.srcs/sources_1/new/ReLU.v}
  {K:/Year 2 CCE-C/Term 2/Logic 2/Verilog-CNN/project_1/project_1.srcs/sources_1/new/PE_FC_ANN_tb.v}
}
synth_design -top PE_FC_ANN -part xc7z020clg400-1
write_checkpoint -noxdef PE_FC_ANN.dcp
catch { report_utilization -file PE_FC_ANN_utilization_synth.rpt -pb PE_FC_ANN_utilization_synth.pb }
