# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/trashCan/Projects/Assign/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/trashCan/Projects/Assign/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  E:/trashCan/Projects/Assign/project_1/project_1.srcs/sources_1/new/ReLU.v
  E:/trashCan/Projects/Assign/tuturu.v
  E:/trashCan/Projects/Assign/tb.v
  E:/trashCan/Projects/Assign/fp_add.v
  E:/trashCan/Projects/Assign/fp_add_tb.v
  E:/trashCan/Projects/Assign/project_1/project_1.sim/sim_1/behav/glbl.v
  E:/trashCan/Projects/Assign/PE_FC_ANN.v
  E:/trashCan/Projects/Assign/weights_Memory.v
  E:/trashCan/Projects/Assign/FC_Layer_ANN.v
  E:/trashCan/Projects/Assign/project_1/project_1.srcs/sources_1/new/PE_FC_ANN_tb.v
  E:/trashCan/Projects/Assign/project_1/project_1.srcs/sources_1/new/ReLU_tb.v
  E:/trashCan/Projects/Assign/project_1/project_1.srcs/sources_1/new/SingleLayer.v
}
synth_design -top ReLU -part xc7z020clg400-1
write_checkpoint -noxdef ReLU.dcp
catch { report_utilization -file ReLU_utilization_synth.rpt -pb ReLU_utilization_synth.pb }
