# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/VivadoFiles/Verilog-CNN/project_2/project_2.cache/wt [current_project]
set_property parent.project_path E:/VivadoFiles/Verilog-CNN/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
read_verilog -library xil_defaultlib {
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/fp_add_2.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/fp_mul.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/PE_FC_ANN.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/weights_Memory.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/FC_Layer_ANN.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/exponential.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/Div_flp.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/tanh.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/SingleLayer.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/tanh_activation_function.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/Softmax.v
  E:/VivadoFiles/Verilog-CNN/project_2/project_2.srcs/sources_1/new/LeNet.v
}
synth_design -top LeNet -part xc7vx485tffg1761-2
write_checkpoint -noxdef LeNet.dcp
catch { report_utilization -file LeNet_utilization_synth.rpt -pb LeNet_utilization_synth.pb }
