# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/IbrahimWael/Desktop/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/Users/IbrahimWael/Desktop/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  D:/Users/IbrahimWael/Desktop/project_2/project_2.srcs/sources_1/new/fp_add_2.v
  D:/Users/IbrahimWael/Desktop/project_2/project_2.srcs/sources_1/new/fp_mul.v
  D:/Users/IbrahimWael/Desktop/project_2/project_2.srcs/sources_1/new/tanh.v
}
synth_design -top tanh -part xc7z020clg400-1
write_checkpoint -noxdef tanh.dcp
catch { report_utilization -file tanh_utilization_synth.rpt -pb tanh_utilization_synth.pb }
